import { AppSettings, CompanyProfile, KaiaDatabase } from '../../types';

export const STORAGE_KEY = 'KAIA_DATABASE_V1';

export const defaultCompany: CompanyProfile = {
  nombreComercial: 'KAIA',
  razonSocial: 'KAIA BUSINESS MANAGEMENT S.L.',
  cif: 'B-98765432',
  direccion: 'Paseo de la Castellana 140, Planta 8',
  codigoPostal: '28046',
  ciudad: 'Madrid',
  provincia: 'Madrid',
  pais: 'España',
  telefono: '+34 910 00 22 44',
  email: 'info@kaia.es',
  web: 'www.kaia.es',
  iban: 'ES66 0049 1500 0512 3456 7890',
  banco: 'Banco Santander',
  swift: 'BSCHESMMXXX',
  condicionesPago: 'Transferencia bancaria a 30 días fecha factura.',
  ivaPorDefecto: 21,
  retencionIRPF: 0,
  cuentaBancaria: 'ES66 0049 1500 0512 3456 7890',
  registroMercantil: 'Registro Mercantil de Madrid, Tomo 41.200, Folio 15, Hoja M-720120.',
  condicionesDefecto: 'Presupuesto válido durante 30 días naturales. Forma de pago: 50% al inicio y 50% a la entrega.',
  pieFacturaDefecto: 'Sociedad inscrita en el Registro Mercantil. Exenta de recargo de equivalencia.',
  moneda: 'EUR',
};

export const defaultSettings: AppSettings = {
  tema: 'claro',
  formatoFecha: 'DD/MM/YYYY',
  moneda: 'EUR',
  autoGuardar: true,
  backupUltimaFecha: '',
  prefijoPresupuesto: 'PRE',
  prefijoFactura: 'FAC',
  prefijoProyecto: 'PRO',
  prefijoCliente: 'CLI',
  incluirAno: true,
  digitosNumero: 4,
  separadorDecimal: ',',
};

export const initialDemoData: KaiaDatabase = {
  company: defaultCompany,
  settings: defaultSettings,
  clients: [
    {
      id: 'CLI-0001',
      nombre: 'Alejandro',
      apellidos: 'Vidal Navarro',
      empresa: 'Nexus Retail Technologies S.L. [DEMO]',
      cif: 'B-84930291',
      email: 'alejandro.vidal@nexusretail.com',
      telefono: '+34 620 445 119',
      direccion: 'C/ Gran Vía 42, 4º B',
      codigoPostal: '28013',
      ciudad: 'Madrid',
      provincia: 'Madrid',
      pais: 'España',
      notas: 'Cliente corporativo clave en el sector omnicanal.',
      estado: 'Activo',
      fechaAlta: '2026-01-15',
      fechaModificacion: '2026-03-01',
      isDemo: true,
    },
    {
      id: 'CLI-0002',
      nombre: 'Elena',
      apellidos: 'Serrano Gil',
      empresa: 'Studio Aura Arquitectura [DEMO]',
      cif: 'A-77382910',
      email: 'eserrano@studioaura.es',
      telefono: '+34 689 331 092',
      direccion: 'Avinguda Diagonal 640',
      codigoPostal: '08017',
      ciudad: 'Barcelona',
      provincia: 'Barcelona',
      pais: 'España',
      notas: 'Estudio de arquitectura y diseño con múltiples sedes.',
      estado: 'Activo',
      fechaAlta: '2026-02-10',
      fechaModificacion: '2026-03-05',
      isDemo: true,
    },
    {
      id: 'CLI-0003',
      nombre: 'Marcos',
      apellidos: 'Alonso Fuentes',
      empresa: 'Logística Cantábrica S.A. [DEMO]',
      cif: 'A-39201948',
      email: 'marcos.alonso@logisticacantabrica.es',
      telefono: '+34 942 550 120',
      direccion: 'Polígono Industrial de Santander 14',
      codigoPostal: '39011',
      ciudad: 'Santander',
      provincia: 'Cantabria',
      pais: 'España',
      notas: 'Proyecto de digitalización de almacenes.',
      estado: 'Activo',
      fechaAlta: '2026-02-28',
      fechaModificacion: '2026-03-08',
      isDemo: true,
    },
  ],
  projects: [
    {
      id: 'PRO-0001',
      titulo: 'Plataforma B2B Omnicanal [DEMO]',
      clienteId: 'CLI-0001',
      servicio: 'Desarrollo de Software & Integración ERP',
      descripcion: 'Migración y desarrollo del portal de compras mayoristas para Nexus Retail.',
      estado: 'En curso',
      fechaInicio: '2026-02-01',
      fechaPrevista: '2026-05-30',
      importe: 14500,
      responsable: 'Carlos Mendoza',
      presupuestoId: 'PRE-2026-0001',
      tareas: [
        { id: '1', texto: 'Auditoría de API ERP legado', completada: true },
        { id: '2', texto: 'Arquitectura de base de datos relacional', completada: true },
        { id: '3', texto: 'Módulo de checkout y facturación B2B', completada: false },
        { id: '4', texto: 'Pruebas de carga y penetración', completada: false },
      ],
      notas: 'Hito 1 entregado y validado por dirección técnica.',
      fechaCreacion: '2026-01-20',
      fechaModificacion: '2026-03-02',
      isDemo: true,
    },
    {
      id: 'PRO-0002',
      titulo: 'Identidad Digital y Gestor BIM [DEMO]',
      clienteId: 'CLI-0002',
      servicio: 'Consultoría y Diseño de Sistemas',
      descripcion: 'Centralización de proyectos arquitectónicos y catálogo digital interactivo.',
      estado: 'En preparación',
      fechaInicio: '2026-03-15',
      fechaPrevista: '2026-06-15',
      importe: 8200,
      responsable: 'Lucía Benítez',
      presupuestoId: 'PRE-2026-0002',
      tareas: [
        { id: '1', texto: 'Toma de requerimientos con socios', completada: true },
        { id: '2', texto: 'Definición de modelos de datos', completada: false },
      ],
      notas: 'Pendiente de inicio formal el 15 de marzo.',
      fechaCreacion: '2026-02-15',
      fechaModificacion: '2026-03-05',
      isDemo: true,
    },
  ],
  quotes: [
    {
      id: 'PRE-2026-0001',
      clienteId: 'CLI-0001',
      fecha: '2026-01-18',
      validez: '2026-02-18',
      estado: 'Aceptado',
      lineas: [
        {
          id: '1',
          descripcion: 'Fase 1: Auditoría de arquitectura técnica e integraciones',
          cantidad: 1,
          precioUnitario: 3500,
          iva: 21,
          descuento: 0,
        },
        {
          id: '2',
          descripcion: 'Fase 2: Desarrollo plataforma web B2B responsive',
          cantidad: 1,
          precioUnitario: 8500,
          iva: 21,
          descuento: 5,
        },
        {
          id: '3',
          descripcion: 'Soporte y despliegue en infraestructura dedicada',
          cantidad: 1,
          precioUnitario: 2500,
          iva: 21,
          descuento: 0,
        },
      ],
      subtotal: 14500,
      descuentoTotal: 425,
      ivaTotal: 2955.75,
      total: 17030.75,
      condicionesPago: '40% a la firma, 30% en entrega hito intermedio, 30% al cierre.',
      formaPago: 'Transferencia Bancaria',
      plazoEntrega: '16 semanas laborables desde la confirmación.',
      revisiones: 'Hasta 2 rondas de revisión por entrega de sprint.',
      cancelacion: 'Cancelación con preaviso de 15 días laborables liquidando hitos completados.',
      notas: 'Presupuesto validado para Nexus Retail.',
      observaciones: 'Incluye formación de 4 horas para administradores de sistema.',
      fechaCreacion: '2026-01-18',
      fechaModificacion: '2026-01-20',
      isDemo: true,
    },
    {
      id: 'PRE-2026-0002',
      clienteId: 'CLI-0002',
      fecha: '2026-02-12',
      validez: '2026-03-12',
      estado: 'Enviado',
      lineas: [
        {
          id: '1',
          descripcion: 'Diseño de interfaz y catálogo de arquitectura BIM',
          cantidad: 1,
          precioUnitario: 5200,
          iva: 21,
          descuento: 0,
        },
        {
          id: '2',
          descripcion: 'Módulo de visualización y descarga para clientes',
          cantidad: 1,
          precioUnitario: 3000,
          iva: 21,
          descuento: 0,
        },
      ],
      subtotal: 8200,
      descuentoTotal: 0,
      ivaTotal: 1722,
      total: 9922,
      condicionesPago: '50% al inicio y 50% a la entrega final.',
      formaPago: 'Transferencia Bancaria',
      plazoEntrega: '12 semanas.',
      revisiones: '3 rondas incluidas.',
      cancelacion: 'Estándar KAIA.',
      notas: 'Enviado a Elena Serrano para aprobación por consejo.',
      observaciones: 'Precios válidos por 30 días naturales.',
      fechaCreacion: '2026-02-12',
      fechaModificacion: '2026-02-15',
      isDemo: true,
    },
  ],
  invoices: [
    {
      id: 'FAC-2026-0001',
      clienteId: 'CLI-0001',
      presupuestoId: 'PRE-2026-0001',
      proyectoId: 'PRO-0001',
      fechaEmision: '2026-01-25',
      fechaVencimiento: '2026-02-25',
      formaPago: 'Transferencia Bancaria',
      metodoPago: 'IBAN ES66 0049 1500 0512 3456 7890',
      lineas: [
        {
          id: '1',
          descripcion: 'Anticipo 40% según contrato Proyecto Plataforma B2B (PRO-0001)',
          cantidad: 1,
          precioUnitario: 5630,
          iva: 21,
          descuento: 0,
        },
      ],
      baseImponible: 5630,
      ivaTotal: 1182.3,
      total: 6812.3,
      importePagado: 6812.3,
      importePendiente: 0,
      estado: 'Pagada',
      pagos: [
        {
          id: 'PAG-0001',
          fecha: '2026-01-28',
          importe: 6812.3,
          metodo: 'Transferencia Bancaria',
          referencia: 'TRF-NX-098231',
          notas: 'Pago recibido y conciliado en Banco Santander.',
        },
      ],
      notas: 'Anticipo de proyecto saldado con éxito.',
      fechaCreacion: '2026-01-25',
      fechaModificacion: '2026-01-28',
      isDemo: true,
    },
    {
      id: 'FAC-2026-0002',
      clienteId: 'CLI-0001',
      presupuestoId: 'PRE-2026-0001',
      proyectoId: 'PRO-0001',
      fechaEmision: '2026-03-01',
      fechaVencimiento: '2026-03-31',
      formaPago: 'Transferencia Bancaria',
      metodoPago: 'IBAN ES66 0049 1500 0512 3456 7890',
      lineas: [
        {
          id: '1',
          descripcion: 'Segundo hito 30%: Validación técnica de módulos e integraciones',
          cantidad: 1,
          precioUnitario: 4222.5,
          iva: 21,
          descuento: 0,
        },
      ],
      baseImponible: 4222.5,
      ivaTotal: 886.73,
      total: 5109.23,
      importePagado: 2500,
      importePendiente: 2609.23,
      estado: 'Parcial',
      pagos: [
        {
          id: 'PAG-0002',
          fecha: '2026-03-06',
          importe: 2500,
          metodo: 'Transferencia Bancaria',
          referencia: 'TRF-NX-104928',
          notas: 'Primer abono de segundo hito.',
        },
      ],
      notas: 'Pendiente segundo abono de 2.609,23 € para completar el hito.',
      fechaCreacion: '2026-03-01',
      fechaModificacion: '2026-03-06',
      isDemo: true,
    },
  ],
  finances: [
    {
      id: 'MOV-0001',
      fecha: '2026-01-28',
      tipo: 'Ingreso',
      categoria: 'Servicios de Consultoría',
      descripcion: 'Cobro factura FAC-2026-0001 (Anticipo Nexus Retail)',
      importe: 6812.3,
      metodo: 'Transferencia Bancaria',
      estado: 'Completado',
      clienteId: 'CLI-0001',
      proyectoId: 'PRO-0001',
      facturaId: 'FAC-2026-0001',
      fechaCreacion: '2026-01-28',
      isDemo: true,
    },
    {
      id: 'MOV-0002',
      fecha: '2026-02-05',
      tipo: 'Gasto',
      categoria: 'Infraestructura & Cloud',
      descripcion: 'Servidores dedicados y clúster Kubernetes',
      importe: 680,
      metodo: 'Tarjeta Corporativa',
      estado: 'Completado',
      fechaCreacion: '2026-02-05',
      isDemo: true,
    },
    {
      id: 'MOV-0003',
      fecha: '2026-02-28',
      tipo: 'Gasto',
      categoria: 'Suscripciones Software',
      descripcion: 'Licencias de diseño y herramientas de desarrollo',
      importe: 340,
      metodo: 'Domiciliación',
      estado: 'Completado',
      fechaCreacion: '2026-02-28',
      isDemo: true,
    },
    {
      id: 'MOV-0004',
      fecha: '2026-03-06',
      tipo: 'Ingreso',
      categoria: 'Servicios de Consultoría',
      descripcion: 'Cobro parcial factura FAC-2026-0002 (Nexus Retail)',
      importe: 2500,
      metodo: 'Transferencia Bancaria',
      estado: 'Completado',
      clienteId: 'CLI-0001',
      proyectoId: 'PRO-0001',
      facturaId: 'FAC-2026-0002',
      fechaCreacion: '2026-03-06',
      isDemo: true,
    },
  ],
  documents: [
    {
      id: 'DOC-0001',
      nombre: 'Contrato_Marco_NexusRetail_2026.pdf',
      categoria: 'Clientes',
      tamano: '2.4 MB',
      tipo: 'PDF',
      fechaSubida: '2026-01-20',
      clienteId: 'CLI-0001',
      proyectoId: 'PRO-0001',
      isDemo: true,
    },
    {
      id: 'DOC-0002',
      nombre: 'Especificaciones_Tecnicas_B2B_v1.2.pdf',
      categoria: 'Proyectos',
      tamano: '1.8 MB',
      tipo: 'PDF',
      fechaSubida: '2026-02-02',
      clienteId: 'CLI-0001',
      proyectoId: 'PRO-0001',
      isDemo: true,
    },
    {
      id: 'DOC-0003',
      nombre: 'Memoria_Descriptiva_StudioAura.pdf',
      categoria: 'Presupuestos',
      tamano: '3.1 MB',
      tipo: 'PDF',
      fechaSubida: '2026-02-12',
      clienteId: 'CLI-0002',
      isDemo: true,
    },
    {
      id: 'DOC-0004',
      nombre: 'Estatutos_Sociales_KAIA_2026.pdf',
      categoria: 'Empresa',
      tamano: '4.5 MB',
      tipo: 'PDF',
      fechaSubida: '2026-01-05',
      isDemo: true,
    },
  ],
  leads: [
    {
      id: 'COM-0001',
      empresa: 'Iberia Renewable Energies S.L. [DEMO]',
      contacto: 'Roberto Gómez',
      email: 'rgomez@iberiarenovables.com',
      telefono: '+34 611 902 445',
      origen: 'LinkedIn',
      servicioInteres: 'Sistema de telemetría y reporting ambiental',
      estado: 'Presupuesto',
      valorEstimado: 22000,
      fechaContacto: '2026-02-18',
      proximoSeguimiento: '2026-03-12',
      notas: 'Reunión inicial muy positiva. Enviando borrador de propuesta técnica.',
      fechaCreacion: '2026-02-18',
      isDemo: true,
    },
    {
      id: 'COM-0002',
      empresa: 'Clínicas Valdés Dental [DEMO]',
      contacto: 'Dra. Carmen Valdés',
      email: 'carmen@clinicasvaldes.es',
      telefono: '+34 913 220 119',
      origen: 'Recomendación',
      servicioInteres: 'Gestión de citas y facturación sincronizada',
      estado: 'Reunión',
      valorEstimado: 9500,
      fechaContacto: '2026-03-01',
      proximoSeguimiento: '2026-03-15',
      notas: 'Reunión fijada para el 15 de marzo en sus oficinas de Madrid.',
      fechaCreacion: '2026-03-01',
      isDemo: true,
    },
    {
      id: 'COM-0003',
      empresa: 'Mediterránea Logistics S.L. [DEMO]',
      contacto: 'Fernando Pardo',
      email: 'fpardo@med-logistics.es',
      telefono: '+34 963 118 770',
      origen: 'Web',
      servicioInteres: 'Optimización de rutas y seguimiento',
      estado: 'Contactado',
      valorEstimado: 16000,
      fechaContacto: '2026-03-04',
      proximoSeguimiento: '2026-03-18',
      notas: 'Solicitó información a través del formulario corporativo.',
      fechaCreacion: '2026-03-04',
      isDemo: true,
    },
  ],
  suppliers: [
    {
      id: 'PRV-0001',
      proveedor: 'CloudScale Infrastructure Europe S.A. [DEMO]',
      cif: 'A-28994820',
      contacto: 'Guillermo Marín',
      email: 'guillermo@cloudscale-eu.com',
      telefono: '+34 911 340 990',
      web: 'www.cloudscale-eu.com',
      servicio: 'Hosting dedicado, CDN y redes privadas virtuales',
      condiciones: 'Pago a 30 días fecha factura por domiciliación.',
      estado: 'Activo',
      notas: 'Proveedor de infraestructura con SLA del 99.99%.',
      fechaCreacion: '2026-01-10',
      fechaModificacion: '2026-02-01',
      isDemo: true,
    },
    {
      id: 'PRV-0002',
      proveedor: 'Asesoría Tributaria Legalis & Partners [DEMO]',
      cif: 'B-83920194',
      contacto: 'Patricia Montero',
      email: 'patricia@legalispartners.es',
      telefono: '+34 915 670 200',
      web: 'www.legalispartners.es',
      servicio: 'Consultoría laboral, fiscal y mercantil',
      condiciones: 'Cuota mensual fija liquidable a mes vencido.',
      estado: 'Activo',
      notas: 'Asesor fiscal externo para declaraciones trimestrales y anuales.',
      fechaCreacion: '2026-01-12',
      fechaModificacion: '2026-01-12',
      isDemo: true,
    },
  ],
  products: [
    {
      id: 'PRD-0001',
      nombre: 'Pack Consultoría Arquitectura de Sistemas (Horas) [DEMO]',
      referencia: 'SRV-CONS-001',
      categoria: 'Servicios',
      descripcion: 'Bolsa de 20 horas de consultoría y diseño de arquitectura técnica.',
      precio: 1600,
      iva: 21,
      stock: 45,
      stockMinimo: 10,
      proveedorId: 'PRV-0001',
      estado: 'Disponible',
      fechaCreacion: '2026-01-15',
      fechaModificacion: '2026-02-10',
      isDemo: true,
    },
    {
      id: 'PRD-0002',
      nombre: 'Dispositivo Físico Llave Criptográfica FIDO2 [DEMO]',
      referencia: 'HW-SEC-FIDO',
      categoria: 'Hardware',
      descripcion: 'Token de seguridad biométrico para acceso administrativo.',
      precio: 65,
      iva: 21,
      stock: 3,
      stockMinimo: 5,
      proveedorId: 'PRV-0001',
      estado: 'Disponible',
      fechaCreacion: '2026-01-20',
      fechaModificacion: '2026-03-02',
      isDemo: true,
    },
    {
      id: 'PRD-0003',
      nombre: 'Licencia Servidor Dedicado Anual [DEMO]',
      referencia: 'LIC-SRV-01',
      categoria: 'Licencias',
      descripcion: 'Suscripción anual a nodo de computación de alto rendimiento.',
      precio: 1200,
      iva: 21,
      stock: 12,
      stockMinimo: 2,
      proveedorId: 'PRV-0001',
      estado: 'Disponible',
      fechaCreacion: '2026-01-22',
      fechaModificacion: '2026-01-22',
      isDemo: true,
    },
  ],
  activities: [
    {
      id: 'ACT-0001',
      fecha: '2026-01-15 10:00',
      descripcion: 'Cliente Nexus Retail Technologies creado',
      tipo: 'cliente',
      entidadId: 'CLI-0001',
      targetView: 'client-detail',
      targetId: 'CLI-0001',
    },
    {
      id: 'ACT-0002',
      fecha: '2026-01-18 12:30',
      descripcion: 'Presupuesto PRE-2026-0001 generado',
      tipo: 'presupuesto',
      entidadId: 'PRE-2026-0001',
      targetView: 'quote-detail',
      targetId: 'PRE-2026-0001',
    },
    {
      id: 'ACT-0003',
      fecha: '2026-01-20 16:45',
      descripcion: 'Proyecto Plataforma B2B Omnicanal iniciado',
      tipo: 'proyecto',
      entidadId: 'PRO-0001',
      targetView: 'project-detail',
      targetId: 'PRO-0001',
    },
    {
      id: 'ACT-0004',
      fecha: '2026-01-25 09:15',
      descripcion: 'Factura FAC-2026-0001 emitida',
      tipo: 'factura',
      entidadId: 'FAC-2026-0001',
      targetView: 'invoice-detail',
      targetId: 'FAC-2026-0001',
    },
    {
      id: 'ACT-0005',
      fecha: '2026-01-28 11:20',
      descripcion: 'Pago de 6.812,30 € registrado para FAC-2026-0001',
      tipo: 'pago',
      entidadId: 'FAC-2026-0001',
      targetView: 'invoice-detail',
      targetId: 'FAC-2026-0001',
    },
    {
      id: 'ACT-0006',
      fecha: '2026-03-01 14:00',
      descripcion: 'Factura FAC-2026-0002 emitida',
      tipo: 'factura',
      entidadId: 'FAC-2026-0002',
      targetView: 'invoice-detail',
      targetId: 'FAC-2026-0002',
    },
    {
      id: 'ACT-0007',
      fecha: '2026-03-06 17:35',
      descripcion: 'Pago parcial de 2.500,00 € registrado para FAC-2026-0002',
      tipo: 'pago',
      entidadId: 'FAC-2026-0002',
      targetView: 'invoice-detail',
      targetId: 'FAC-2026-0002',
    },
  ],
};
